import ComponentsMenu from "@/components/ComponentsMenu";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-20 items-start max-w-6xl mx-auto min-h-screen">
          <ComponentsMenu />
          <main className="flex flex-col flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
